server.port=8082
spring.application.name=PROFILE-SERVICE

# Database Configuration (MySQL)
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/profile_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:manager}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA/Hibernate Properties
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# Eureka registration
eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka/

# JWT Config (Must match UserService and Gateway secret)
jwt.secret=${JWT_SECRET:my_super_secret_key_which_is_long_enough_for_sha256_key_and_more_characters_for_security}
