server.port=8761
spring.application.name=service-registry

# Configure standalone Eureka Server
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false

logging.level.com.netflix.eureka=INFO
logging.level.com.netflix.discovery=INFO
